icon(O, "characterless component", "Placeholder for components that are unknown objects or for which a character does not exist.");
icon("覀", "[character component]", "覀 is a character component that does not have any meaning on its own. Represents two hands grabbing a waist in the character 要.")
semsem("好", "女", "子", 3, "good; to like, love", "It is good (好) for a woman (女) and her child (子) to be together.");
icon("女", "woman; female", "Pictograph of a woman. Depicts a stick-figure with breasts sitting or squatting down.", "obs");
icon("子", "son; child", "Pictograph of a small child with its two arms outstretched.", "bs");
addEtymology("是", "is; to be", "Origin unclear.", [unknownComponent("旦", [0, 5]), soundComponent("龰", [5])]);
icon("止", "(foot); stop", `Pictograph of a foot. ` + shiftMeaning("stop"), "os");
semphon("的", "白", "勺", 5, "(bright white); [grammatical particle]", obsoleteMeaning("bright white"), true)
icon("白", "white", `Origin unclear. Used in ancient texts to mean "white" and "hundred" (百).`, "o");
icon("勺", "spoon; ladle", "Pictograph of a ladle.", "o");
icon("我", "I; me", "Pictograph of a weapon or farming tool with a forked blade and long handle. The meaning \"I; me\" is a phonetic loan.", "os", [iconComponent("戈", [1, 2, 4])]);
icon("戈", "dagger-axe", "Pictograph of a weapon with a long shaft and horizontal blade.", "obs");
icon("了", "[grammatical particle]", "Pictograph of a young child, similar to 子 but without arms. Relation to meaning uncertain. Sometimes explained as a derivation from 子 by cutting off the arms, depicting something being cut short or finished.", "s");
icon("不", "no; not", "Pictograph of sepals of a flower. The meaning \"no\" is a phonetic loan.", "os");
icon("一", "one", "A single horizontal stroke, representing the number one.");
icon("二", "two", "Two horizontal strokes, representing the number two.");
icon("三", "three", "Three horizontal strokes, representing the number three.");
semphon("你", "亻", "尔", 2, "you", "", true, true)
icon("人", "person", "Pictograph of the side view of a person.", "obs");
icon("爾", "you (archaic)", `Origin unclear. Used in ancient texts to mean "you".`, "bs");
simp("尔", "爾");
semphon("百", "一", "白", 1, "one hundred");
icon("才", "talent; just", `Pictograph of a small plant starting to emerge from the ground. ` + shiftMeaning("talent", "to sprout"), "obs");
icon("土", "earth; dirt", "Pictograph of a lump of clay on a pottery wheel.", "obs");
icon("士", "soldier; scholar", "Pictograph of the head of an axe. Likely used to represent a military officer.", "bs");
addEtymology("在", "be at; exist", "Origin unclear.", [soundComponent("才", [0, 3], ""), unknownComponent("士", [3], "The modern form of this component looks like 土, but originally it was written as 士.")], "bs");
icon("言", "speech", "Pictograph of a tongue sticking out of a mouth. In old scripts written the same as 舌 but with an extra line.", "obs", [iconComponent(O, [0, 2], "Depicts sound coming out of the mouth."), iconComponent("舌", [2])]);
icon("舌", "tongue", "Pictograph of a tongue sticking out of a mouth, with a splatter of spit at the end.", "os", [iconComponent(O, [0, 3], "Depicts a tongue."), iconComponent("口", [3])]);
icon("口", "mouth", "Pictograph of a mouth.", "ob");
icon("行", "walk; travel", "Pictograph of a street intersection.", "bs");
icon("文", "writing; language", "Pictograph of a man with writing (possibly a tattoo) on his chest. In later scripts the writing was abbreviated to a dot or omitted altogether.", "obs");
semsem("辵", "彳", "龰", 3, "walk; move", "This character very rarely appears by itself. It is generally used as a component in other characters written as 辶.");
semphon("這", "辶", "言", 7, "this", obsoleteMeaning("to meet"), true, false, true)
addEtymology("这", "this", simplified("這") + obsoleteMeaning("to meet"), [meaningComponent("辶", [4]), simplifiedComponent("文", [0, 4], "Simplified from the 言 component in the traditional character 這. Used since 文 has fewer strokes while having a similar meaning and sound as 言.")]);
icon("有", "have; hold", "Pictograph of a hand holding meat", "bs", [iconComponent("又", [0, 2]), iconComponent("⺼", [2], "Deceptively similar to the character for moon (月).")]);
icon("又", "(hand); again", "Pictograph of a hand. " + obsoleteMeaning("right hand"), "ob");
icon("肉", "meat", "Pictograph of a piece of meat.", "s");
icon("月", "moon", "Pictograph of the moon.", "obs");
icon("也", "also", "Origin unclear. Variously explained as a pictograph of a snake, a vulva, a funnel, a crying child, or an ideograph depicting a pause in speech.", "bs");
semphon("他", "亻", "也", 2, "he; it", "", true);
semphon("她", "女", "也", 3, "she", "", true);
icon("門", "door; gate", "Pictograph of a gate.", "obs");
simp("门", "門");
semphon("們", "亻", "門", 2, "[plural marker]");
semphon("们", "亻", "门", 2, "[plural marker]");
icon("竹", "bamboo", "Pictograph of bamboo stalks.", "s");
icon("个", "[measure word]", "Pictograph of one stalk of bamboo. Same as one half of the character for bamboo (竹).", "s");
icon("囗", "wall; surrounding", "Pictograph of a wall surrounding an area. Component form of 围 (traditional 圍).");
icon("韋", "leather", "Pictograph of two feet walking around city walls. " + obsoleteMeaning("to surround"), "os");
simp("韦", "韋");
semphon("围", "囗", "韦", [[0, 2, -1], [2, -1]], "surround");
semphon("圍", "囗", "韋", [[0, 2, -1], [2, -1]], "surround");
icon("古", "ancient; old", "Origin unclear. Possibly a pictograph of a shield.", "obs");
semphon("固", "囗", "古", [[0, 2, -1], [2, -1]], "sturdy; firm");
semphon("個", "亻", "固", 2, "[measure word]");
icon("來", "come", "Pictograph of wheat. " + soundLoan("come", "wheat", "麥"), "obs");
simp("来", "來");
addEtymology("麥", "wheat", `The top component 來 is a pictograph of wheat. It is unclear why the foot component (夂) was added to the character for "wheat".`, [soundComponent("來", [0, 8], "Also serves as an iconic component."), unknownComponent("夂", [8])]);
simp("麦", "麥", [[0, 4], [4]]);
icon("要", "want; will", "Pictograph of two hands grabbing a woman's waist. " + soundLoan("want", "waist", "腰"), "bs", [iconComponent("覀", [0, 6], "Represents two hands grabbing a waist."), iconComponent("女", [6])])
semphon("腰", "⺼", "要", 4, "waist");
semphon("就", "京", "尤", 8, "at once; accomplish", shiftMeaning("high place", "achieve"));
icon("京", "(high place); capital city", "Pictograph of a tall building. Similar to 高. " + shiftMeaning("capital city", "high place"), "obs");
icon("高", "tall", "Pictograph of a tall building. Similar to 京.", "obs");
icon("尤", "especially; outstanding", "Pictograph of a hand with a wart on it. " + soundLoan("especially", "wart", "疣"), "o");
semphon("疣", "疒", "尤", 5, "wart");
icon("疒", "sickness", "Pictograph of a stretcher for sick people.", "s");
semphon("到", "至", "刂", 6, "arrive");
icon("至", "arrive", "Pictograph of an arrow hitting its target.", "obs");
icon("刀", "knife", "Pictograph of a knife.", "os");
icon("兒", "child", "Pictograph of a child with an opening in the top of its head. Represents the soft spot (fontanel) at the top of young infant heads.", "obs");
simp("儿", "兒");
icon("兄", "elder brother", "Pictograph of a mouth on top of a person, representing an older brother giving orders.", "obs", [iconComponent("口", [0, 3]), iconComponent("人", [3])]);
icon("兌", "exchange", "Pictograph of words coming out of the mouth of a person, representing negotiation of an exchange.", "obs", [iconComponent("八", [0, 2], "Represents words coming out of the mouth."), iconComponent("口", [2, 5]), iconComponent("人", [5])]);
simp("兑", "兌");
icon("八", "eight", "Pictograph of two lines facing away from each other. " + soundLoan("eight", "separate", "别"), "b");
semphon("说", "讠", "兑", 2, "speak; say");
semphon("說", "言", "兌", 7, "speak; say");
icon("力", "strength; power", "Pictograph of a plow, representing strength", "bs");
addEtymology("另", "besides; different; separate", "Origin unclear. Possibly derived from the left side of 別, which has a related meaning.", [unknownComponent("口", [0, 3]), unknownComponent("力", [3])]);
icon("冎", "bone", "Pictograph of bones.", "s");
semsem("咼", "冎", "口", 6, "jaw");
icon("骨", "bone", "Pictograph of a bone (冎) with muscle (⺼) attached to it.", "s", [iconComponent("冎", [0, 5]), iconComponent("⺼", [5])]);
icon("別", "different; separate; don't", "Pictograph depicting cutting meat off of a bone.", "s", [iconComponent("冎", [0, 5], "Here written similar to 另."), iconComponent("刂", [5])]);
simp("别", "別");
icon("水", "water", "Pictograph of a river.", "s");
icon("艸", "grass", "Pictograph of blades of grass.", "s");
icon("棗", "date tree", "Pictograph of a date tree.", "s");
simp("枣", "棗");
icon("日", "sun; day", "Pictograph of the sun.", "obs");
icon("十", "ten", "A single vertical line, representing one set of ten. Analagous to the archaic characters 廿 (twenty) and 卅 (thirty).", "obs");
icon("廿", "twenty", "Two vertical lines, representing two sets of ten.", "obs")
icon("卅", "thirty", "Three vertical lines, representing three sets of ten.", "obs")
semphon("早", "日", "棗", 4, "early; morning", "The form of the original phonetic component 棗 was abbreviated to look like 十.");
semphon("草", "艹", "早", 3, "grass");
icon("木", "wood; tree", "Pictograph of a tree.", "obs");
icon("手", "hand", "Pictograph of a hand with five fingers.", "bs");
icon("王", "king", "Pictograph of an axe head, used as a symbol of the king's military authority.", "obs");
icon("今", "today", "Pictograph of sounds coming out of the mouth. " + soundLoan("today", "moan", "吟"), "obs");
semphon("吟", "口", "今", 3, "chant; recite; moan");
semphon("金", "王", "今", [[0, 2, 5, 7], [2, 5, 7]], "metal; gold", "王 is used here because it originally was a pictograph of an axe head, which is made from metal.", false, false, true, "b");
icon("心", "heart", "Pictograph of a heart.", "bs");
icon("虫", "worm; bug", "Pictograph of a worm.", "s");
icon("目", "eye", "Pictograph of an eye.", "obs");
icon("魚", "fish", "Pictograph of a fish.", "obs");
simp("鱼", "魚");
icon("山", "mountain", "Pictograph of a mountain.", "obs");
icon("火", "fire", "Pictograph of fire.", "os");
icon("犬", "dog", "Pictograph of a dog.", "obs");
icon("石", "stone; rock", "Pictograph of a stone chime.", "o");
icon("足", "foot; leg", "Pictograph of a foot attached to a leg.", "os", [iconComponent(O, [0, 3], "Depicts a leg."), iconComponent("龰", [3])]);
icon("糸", "silk; thread", "Pictograph of twisted silk threads.", "obs");
icon("能", "can; able", "Pictograph of a bear holding meat in its mouth. " + shiftMeaning("ability; power", "bear"), "os", [iconComponent(O, [0, 2], "Depicts the head of the bear."), iconComponent("⺼", [2, 6]), iconComponent(O, [6], "Depicts the four legs and tail of the bear.")]);
icon("熊", "bear", "Pictograph of a bear holding meat in its mouth. Based on 能, with four dots added at the bottom to differentiate it, representing four legs.", "s", [iconComponent("能", [0, 10], "Here used as a pictograph of a bear."), iconComponent("灬", [10], "Here used to represent four legs.")]);
icon("四", "four", "In ancient texts the character 亖 (four horizontal strokes) was used. The origin of the current form is unclear.");
icon("亖", "four", "Four horizontal strokes, representing the number four.");
icon("五", "five", "Origin unclear. Originally an X between two lines.", "b");
icon("六", "six", "Originally a pictograph of a tent or building. Unrelated to modern meaning.", "b");
icon("七", "seven", "Originally resembled a cross, depicting the meaning \"to cut\", since 七 sounds like 切 (qiē; to cut).", "b");
semphon("切", "刀", "七", 2, "to cut", "", false, false, true);
icon("九", "nine", "Origin unclear. There are varied explanations of what 九 is meant to represent, including a hook, an elbow, and a hand reaching out to grab something.", "obs");
icon("囧", "window", "Originally a pictograph of a window. Nowadays sometimes used as a sad-face emoticon.", "bs");
icon("明", "bright; clear", "The character was originally a pictograph of the moon (月) shining through a window (囧). Traditionally (but incorrectly) explained that the sun (日) and moon (月) together are bright (明).", "obs", [iconComponent("囧", [0, 4], "The modern form looks similar to 日 (sun)."), iconComponent("月", [4])]);
icon("天", "sky; day", "Pictograph of a line above a person, representing the sky.", "ob", [iconComponent(O, [0, 1], "Depicts the sky."), iconComponent("大", [1], "Here used as a pictograph of a person.")])
icon("几", "small table; (simp.) how much", "Pictograph of a small table. " + simplifyMerge("几", "幾", "how much"), "s");
semsem("幾", "𢆶", "戍", 6, "how much; how many");
icon("𢆶", "small, insignificant", "Pictograph of two threads. Double of 幺.", "b");
icon("戍", "garrison", "Pictograph of a person (人) with a weapon (戈).", "s", [iconComponent("人", [1, 3]), iconComponent("戈", [0, 1, 3])]);
icon("馬", "horse", "Pictograph of a horse.", "obs");
simp("马", "馬");
semphon("吗", "口", "马", 3, "[question particle]");
semphon("嗎", "口", "馬", 3, "[question particle]");
semphon("妈", "女", "马", 3, "mother");
semphon("媽", "女", "馬", 3, "mother");
icon("貝", "shell", "Pictograph of a cowrie shell. In ancient China such shells were used as currency.", "b");
simp("贝", "貝");
icon("朋", "friend", `Pictograph of two strings of objects mounted together. Originally meant "pair", later the meaning shifted to "friend". The modern form is visually similar to 月 (moon) but the meaning is not related.`, "bs")
icon("友", "friend", "Pictograph of two hands togther to convey the meaning \"friend\".", "bs", [iconComponent("又", [0, 2], "Also serves as a phonetic component."), iconComponent("又", [2], "Also serves as a phonetic component.")]);
icon("沒", "drown; not have", `Pictograph of a hand reaching in the water to grab something. Later the meaning shifted to "drown". This meaning is only used when the character is pronouned "mò". When pronounced "méi" (which is much more common), it means "not have". This meaning is a phonetic loan, unrelated to the original meaning.`, "s", [iconComponent("氵", [0, 3]), iconComponent(O, [3, 5], "Depicts an object beneath the surface of the water."), iconComponent("又", [5])]);
simp("没", "沒");
icon("田", "field", "Pictograph of a field.");
semsem("男", "田", "力", 5, "male", "Traditionally males (男) were the people who plowed (力) the fields (田).");
icon("乍", "mow; abruptly", "Pictograph of a tool for cutting grass.", "bs")
semphon("昨", "日", "乍", 4, "yesterday");
icon("亥", "12th earthly branch", "Pictograph of roots.", "b");
semphon("孩", "子", "亥", 3, "child");
icon("大", "big", `Pictograph of a person with outstretched arms, representing the meaning "big".`, "ob");
icon("小", "small", "Pictograph of three small dots, representing grains of sand or rice, to convey the meaning \"small\".", "ob");
icon("匕", "spoon; ladle", "Pictograph of a ladle.", "bs");
icon("艮", "blunt", "Origin unclear. Originally written with 目 over 匕.", "s", [unknownComponent("目", [0, 4]), unknownComponent("匕", [4])]);
semphon("很", "彳", "艮", 3, "very");
icon("太", "very; extremely", `Addition of a dot to 大 (dà; big) to mean "very" or "extremely".`, "", [iconComponent("大", [0, 3])]);
icon("卩", "person", "Variant component form of 人. Depicts a person kneeling.", "o");
icon("巴", "to cling to", "Pictograph of a person grabbing something with their hand.", "os");
icon("邑", "area; city", "Pictograph of a person (卩) outside a city wall (囗). Appears as a component in the right side of characters as ⻏.", "os", [iconComponent("囗", [0, 3]), iconComponent("卩", [3], "The modern form of this component looks like 巴.")])
icon("冉", "gradually; drooping (branches or hair)", "Pictograph of two strands of something drooping.", "bs")
semphon("那", "⻏", "冄", 4, "that", obsoleteMeaning("name of a city"), true, false, true);
semphon("哪", "口", "那", 3, "which");
semsem("里", "田", "土", 4, "village; (simp.) inside", "A village (里) is an area of land (土) where people have fields (田). " + simplifyMerge("里", "裡", "inside"));
icon("衣", "clothes", "Pictograph of a coat.", "obs");
semphon("裡", "衤", "里", 5, "inside");
addEtymology("裏", "inside", "Variant form of 裡.", [soundComponent("里", [2, 9]), meaningComponent("衣", [0, 2, 9])]);
icon("宀", "roof", "Pictograph of a roof.", "o");
icon("豕", "hog", "Pictograph of a hog.", "obs");
semphon("家", "宀", "豕", 3, "house; family", "", true, false, false, "obs");
icon("聿", "writing utensil", "Pictograph of a hand holding a writing utensil.", "bs", [iconComponent("又", [0, 3]), iconComponent(O, [3], "Depicts a writing utensil.")]);
icon("者", "-er; [one that...]", "Origin unclear.")
semphon("書", "聿", "者", 5, "book; writing", "", true);
simp("书", "書", [[0, 1, 2], [1, 2]]);
icon("本", "root; foundation", "Addition of a horizontal line toward the bottom of 木 (tree) to represent the roots of the tree.", "s", [iconComponent("木", [0, 4]), iconComponent(O, [4], "Depicts roots.")]);
icon("旡", "choke", "Pictograph of a person with their mouth facing backwards.", "o", [iconComponent("口", [0, 2]), iconComponent("卩", [2])]);
addEtymology("愛", "love", "", [soundComponent("旡", [0, 6], obsoleteSound("愛", "旡")), meaningComponent("心", [6, 10]), unknownComponent("夂", [10])], "s");
addEtymology("爱", "love", "Simplified form of 愛.", [soundComponent("旡", [0, 6], obsoleteSound("愛", "旡")), meaningComponent("友", [6])]);
icon("真", "true", "Origin unclear.", "os", [unknownComponent("匕", [0, 2]), unknownComponent("貝", [2, 7, 8])]);
icon("去", "go; leave", "Origin unclear. The 口 component is variously explained as (1) an opening to a building or cave that the person is departing from, or (2) an anus, i.e. the orifice through which things leave a person.", "os", [iconComponent("大", [0, 3], "Here used as a pictograph of a person."), iconComponent("口", [3], "Here used as a pictograph of some sort of opening.")])
semsem("相", "木", "目", 4, "each other", "Represents an eye (目) observing a tree (木). " + shiftMeaning("compare; mutual; each other", "observe"));
semphon("想", "心", "相", 9, "think; desire", "", false, false, true);
semsem("看", "手", "目", 4, "look; watch", "Depicts putting a hand (手) over the eyes (目) and looking (看) into the distance.");
icon("矢", "arrow", "Pictograph of an arrow.", "obs")
semphon("知", "口", "矢", 5, "know", "The mouth component (口) represents the oral transmission of knowledge.", false, false, true);
icon("首", "head; first", "Pictograph of a head (hair above an eye).", "obs", [iconComponent(O, [0, 4], "Depicts hair."), iconComponent("目", [4])]);
semphon("道", "辶", "首", 9, "way; path", "", false, false, true);
icon("此", "this", `Depicts a person (人) stopping (止), meaning "here".`, "obs", [iconComponent("止", [0, 4]), iconComponent("人", [4])]);
semsem("些", "此", "二", 6, "some; a few");
icon("隹", "bird", "Pictograph of a short-tailed bird.", "obs");
semphon("誰", "言", "隹", 7, "who");
semphon("谁", "讠", "隹", 2, "who");
icon("合", "together; join", "Pictograph of two mouths facing each other.", "obs", [iconComponent("口", [0, 3]), iconComponent("口", [3])]);
icon("會", "will; able; meeting", "Origin unclear. Possibly related to 合 (together).", "bs");
simp("会", "會");
icon("回", "return; turn around", `Originally a spiral, conveying the meaning "to turn around".`, "b");
semphon("問", "口", "門", 8, "ask", "", false, false, true);
semphon("问", "口", "门", 3, "ask", "", false, false, true);
icon("頁", "leaf; page; (head)", `Pictograph of a head (首) on top of a person (卩). Means "head" when pronounced xié. Has unrelated meaning "leaf" when pronounced yè, due to this character being adopted as a shorthand form of 葉.`, "obs", [iconComponent("首", [0, 7]), iconComponent("卩", [7])]);
simp("页", "頁", [[0, 4], [4]]);
icon("世", "world; era; generation", `Three copies of 十 (ten) to make 30, similar to the archaic character 卅 (30). Conveys the meaning "30-year generation", also symbolizing a branching family tree.`, "bs");
semphon("枼", "木", "世", 5, "flat piece of wood", "", false, false, true);
semphon("葉", "艹", "枼", 4, "leaf");
semphon("題", "頁", "是", 9, "topic; problem", obsoleteMeaning("forehead"), true, false, true);
simp("题", "題");
semsem("什", "亻", "十", 2, "what", obsoleteMeaning("group of ten soldiers"));
icon("幺", "tiny; one", "Pictograph of a single twisted thread.", "b");
icon("林", "woods; forest", "Combination of two trees (木).", "", [iconComponent("木", [0, 4]), iconComponent("木", [4])]);
icon("森", "forest", "Combination of three trees (木).", "", [iconComponent("木", [0, 4]), iconComponent("木", [4, 8]), iconComponent("木", [8])]);
icon("𣏟", "hemp", "Pictograph of hemp leaves. Visually similar to 林 but not related.");
icon("广", "roof; (simp.) wide", "Variant form of 宀 (roof). " + simplifyMerge("广", "廣", "wide"));
semphon("廣", "广", "黃", 3, "wide; broad");
icon("黃", "yellow", `Pictograph of a person with a person with a large belly, representing someone deformed. Based on the original meaning "physically impaired". Later meaning shifted to "yellow; sallow", a skin color associated with illness. `, "ob")
simp("黄", "黃");
icon("光", "light; ray", "Pictograph of fire on top of a person.", "os", [iconComponent("火", [0, 4]), iconComponent("卩", [4])]);
icon("麻", "hemp; flax; sesame", "", "", [unknownComponent("广", [0, 3]), iconComponent("𣏟", [3])]);
icon("么", "tiny; one; (simp.) [particle]", "Variant form of 幺. " + simplifyMerge("么", "麼", "[particle]"));
semphon("麼", "幺", "麻", 11, "[particle]", "", false, false, true);
semphon("麽", "么", "麻", 11, "[particle]", "Variant form of 麼.", false, false, true);
icon("刃", "knife edge", "Pictograph of a knife. Similar to 刀 (knife), with an added dot.");
semphon("忍", "心", "刃", 3, "endure; suffer", "", false, false, true);
semphon("認", "言", "忍", 7, "recognize; accept");
semphon("认", "讠", "人", 2, "recognize; accept");
icon("象", "elephant; shape; appearance", "Pictograph of an elephant.", "bs");
icon("為", "for; to; as; to act as; to do", `Pictograph of a hand guiding an elephant to do work (in ancient China elephants were tamed to do work). Based on the meaning "to work; to do".`, "bs", [iconComponent("又", [0, 4]), iconComponent("象", [4])]);
icon("爲", "for; to; as; to act as; to do", "Variant form of 為.")
simp("为", "為", [[0, 1], [1]]);
icon("多", "much; many", `Pictograph of two identical objects to convey the meaning "many". Not related to 夕 (dusk).`, "obs");
icon("夕", "dusk; evening", `Pictograph of the moon. Used to express "evening" or "night".`, "obs")
semsem("隻", "隹", "又", 8, "[measure word]", "Used as a measure word for birds, and some other animals and objects.")
icon("只", "only; but; (simp.) [measure word]", "Origin unclear. " + simplifyMerge("只", "隻", "[measure word]"));
icon("音", "sound; voice", `Pictograph of sound (represented with one or two horizontal lines) coming from a tongue (舌). In seal script, identical to 言 (speech) except with a dot or line added to the middle of the 口 (mouth) component.`, "s", [iconComponent("舌", [2]), iconComponent(O, [0, 2], "Depicts sound coming from the tongue.")]);
icon("戠", "sword; gather", "Pictograph of some sort of military-purpose object. The modern form of the left component looks like 音 but it is unclear whether or not it is actually related.", "ob", [unknownComponent("音", [0, 9]), iconComponent("戈", [9])]);
semphon("識", "言", "戠", 7, "know; perceive");
semphon("识", "讠", "只", 2, "know; perceive");
semphon("作", "亻", "乍", 2, "work; writing");
icon("卜", "to divine", "Pictograph of a crack on a bone. In ancient China such cracks were used for divination.");
semphon("攴", "又", "卜", 2, "hit; tap", "", false, false, true);
semphon("故", "攵", "古", 5, "happening; instance; reason", "", false, false, true);
addEtymology("做", "make; do", "Originally was written the same as 作 (work). The 夂 (foot; movement) component was added later to distinguish the characters. The middle component 乍 was corrupted to look like 古, which caused later writers to reanalyze 做 as a compound of 亻and 故.", [meaningComponent("作", [0, 7], "Also serves as a phonetic component. In the modern form, 乍 is corrupted to look like 古."), meaningComponent("夂", [7])], "s");
phonsem("怎", "作", "心", 5, "how");
icon("羊", "sheep; goat", "Pictograph of the horns on a sheep.", "obs");
semphon("样", "木", "羊", 4, "way; shape; manner");
phonsem("都", "者", "⻏", 8, "all; large city, capital", `Based on the meaning "large city, capital", which is the meaning when pronounced "dū". When pronounced "dōu", it has the unrelated meaning "all", etymologically related to 多 (many).`, true);
icon("可", "be willing; allow", `The right component is a pictograph of an axe handle, now written as 柯 (kē). 口 (mouth) was added later to indicate that the character is only "mouthed", i.e. only used for its phonetic value.`, "b", [meaningComponent("口", [1, 4]), iconComponent(O, [0, 1, 4], "Depicts an axe handle.")]);
semphon("柯", "木", "可", 4, "axe handle; stalk");
icon("見", "see", "Pictograph of a person (卩) using their eye (目) to see (見).", "obs", [iconComponent("目", [0, 5]), iconComponent("卩", [5])]);
simp("见", "見", [[0, 2], [2]]);
icon("炎", "flame; inflammation", "Combination of two fires (火).", "", [iconComponent("火", [0, 4]), iconComponent("火", [4])]);
icon("黑", "dark; black; illegal", "Pictograph of a person whose face has been tatooed. In ancient China criminals were punished by having their faces permanently marked. Later writers reanalyzed the character as a chimney being blackened by fire, so the bottom component was changed to look like 炎 (flame).", "obs");
semsem("占", "卜", "口", 2, "observe; divine; seize", "In ancient China fortune-tellers made cracks (卜) and holes (口) in turtle shells for the purpose of divination.");
semphon("點", "黑", "占", 12, "dot; point; choose", "", true);
addEtymology("点", "dot; point; choose", simplified("點"), [soundComponent("占", [0, 5], obsoleteSound("点", "占")), simplifiedComponent("灬", [5], "Simplified from the 黑 (black) component in the traditional character 點.")]);
icon("袁", "long robe", "The meaning of the part of the character above 衣 (clothes) is unclear.", "", [unknownComponent(O, [0, 5], unknownComonentNote()), iconComponent("衣", [5])]);
semphon("睘", "目", "袁", 5, "gaze in terror");
phonsem("還", "睘", "辶", 13, "still; return", "", true);
addEtymology("还", "still; return", simplified("還"), [simplifiedComponent("不", [0, 4], shorthand("睘", "還")), meaningComponent("辶", [4])]);
icon("以", "use; by means of", "Origin unclear. The right component is 人 (person).", "obs", [unknownComponent(O, [0, 2], unknownComonentNote()), iconComponent("人", [2])]);
icon("米", "rice", "Pictograph of grains of rice.", "o");
icon("气", "gas; air; weather", "Pictograph of air.", "s");
icon("食", "eat; food", "Pictograph of food being spooned into the mouth. Not related to 良.", "obs", [iconComponent("口", [0, 3]), iconComponent("匕", [7])]);
icon("良", "good; fine", "Pictograph of a hallway, now written as 廊. " + obsoleteMeaning("hallway"), "obs");
semphon("廊", "广", "郎", 3, "corridor; porch");
phonsem("郎", "良", "⻏", 6, "husband; youth", "Originally a place name for what is now Shandong province. Unrelated to current meaning.")
semphon("餼", "飠", "氣", 8, "gift of grain");
semphon("饩", "饣", "气", 3, "gift of grain");
phonsem("氣", "气", "米", 4, "gas; air; weather", "The 米 (rice) component was added because this character was often used as a variant of 餼 (gift of grain).");
icon("乞", "beg; request", "Originally a variant of 气. The current meaning is a phonetic loan.");
semphon("吃", "口", "乞", 3, "eat");
icon("夬", "decisive", "Origin unclear. Possibly a pictograph of a hand separating something.", "s");
semphon("快", "忄", "夬", 3, "fast; happy");
icon("寸", "inch; thumb; (hand)", "Pictograph of a hand with a line marking a spot on the wrist. In traditional Chinese medicine this spot on the wrist where the pulse can be taken is called the 寸口. ", "s");
icon("對", "correct; pair; match", "Origin unclear. Appears to be a hand using some sort of tool, possibly a rake or a hoe.", "obs", [unknownComponent(O, [0, 11], "Possibly a rake or hoe."), iconComponent("寸", [11], "Used here to represent a hand.")]);
icon("对", "correct; pair; match", simplified("對") + "Origin unclear. Appears to be a hand using some sort of tool, possibly a rake or a hoe.", "對:obs", [simplifiedComponent("又", [0, 2], "Shorthand for the left component of 對, possibly depicting a rake or hoe."), iconComponent("寸", [2], "Used here to represent a hand.")]);
semphon("答", "⺮", "合", 6, "answer; agree", "The significance of the ⺮ (bamboo) component is unclear.", true);
icon("巾", "cloth; towel", "Pictograph of a cloth hanging downwards.", "b");
icon("冃", "hat", "Represents a hat. Top component form of 冒.")
icon("冒", "hat", "Pictograph of a hat over an eye. Old way of writing 帽 (hat).", "bs", [iconComponent("冃", [0, 4]), iconComponent("目", [4])]);
semsem("帽", "巾", "冒", 3, "hat");
icon("免", "exempt; avoid", "Pictograph of a person with a hat, now written as 冕. The current meaning is a phonetic loan.", "b")
semphon("冕", "冃", "免", 4, "crown; ceremonial headwear");
semphon("晚", "日", "免", 4, "night; evening", "", true);
icon("上", "up", `Originally a small line or dot above a longer line, indicating "up". The vertical line was added to distinguish the character from 二 (two).`, "ob");
icon("下", "down", `Originally a small line or dot below a longer line, indicating "down". The vertical line was added to distinguish the character from 二 (two).`, "ob");
icon("尸", "corpse", "Pictograph of a bent-over human.", "obs");
semphon("尼", "尸", "匕", 3, "near; nun");
let mouthedNote = `口 (mouth) indicates that the character is only "mouthed", i.e. only used for its phonetic value.`;
semphon("呢", "口", "尼", 3, "[particle]", mouthedNote);
icon("玉", "jade; gem", `Pictograph of a ritual object made out of several pieces of jade joined together by a string. A dot was later added to 玉 to distinguish it from 王 (king).`, "ob");
addEtymology("現", "appear; now", "", [unknownComponent("𤣩", [0, 4]), soundComponent("見", [4], "Also serves as a meaning component.")]);
simp("现", "現");
phonsem("寺", "止", "寸", 3, "temple", `Based on the original meaning of "to grasp". The current meaning "temple" is a phonetic loan. The original meaning is now represented by the character 持 (to hold).`, true, false, "bs");
semphon("持", "扌", "寺", 3, "hold; grasp");
semphon("時", "日", "寺", 4, "time");
addEtymology("时", "time", simplified("時"), [meaningComponent("日", [0, 4]), simplifiedComponent("寸", [4], "Shorthand for the 寺 component in the traditional character 時.")]);
icon("厂", "cliff; (simp.) factory", "Pictograph of a cliff or similarly shaped object. " + simplifyMerge("厂", "廠", "factory") + " In simplified characters the 广 component is often written as 厂.");
semphon("廠", "广", "敞", 3, "factory; depot");
phonsem("敞", "尚", "攵", 8, "open; spacious");
icon("冂", "hall; platform", "Pictograph of a large room or platform. Original form of 堂.")
icon("尚", "value; esteem", "Pictograph of a large room or platform.", "b", [iconComponent("冂", [0, 5]), unknownComponent("口", [5], "Likely added just to make the character look more even (with less awkward space).")]);
icon("堂", "hall; large room", "Pictograph large room or platform rising from the ground.", "bs", [iconComponent("尚", [0, 8], "Pictograph of a large room or platform."), iconComponent("土", [8])]);
icon("矦", "archery target", "Pictograph of an arrow (矢) hitting a target (厂).", "obs", [iconComponent("厂", [0, 4], "Here used to represent a target."), iconComponent("矢", [4])]);
semphon("候", "亻", "矦", 3, "wait; inquire; watch", "", false, false, false, "s");
icon("反", "against; oppose", `Pictograph of a hand (又) climbing a cliff (厂). Based on original meaning "pull", later extended to "turn around", "oppose".`, "b", [iconComponent("厂", [0, 2]), iconComponent("又", [2])]);
semphon("飯", "飠", "反", 8, "food; rice");
semphon("饭", "饣", "反", 3, "food; rice");
icon("出", "go out; exit", `Pictograph of a foot (止) going out of an enclosure.`, "obs", [iconComponent("止", [0, 3]), iconComponent(O, [3], "Depicts an enclosure.")]);
icon("再", "again", `Origin unclear. Possibly contains 二 (two) as a component, to convey the meaning "second time; again".`, "obs", [meaningComponent("二", [4])]);
icon("㝵", "obtain; get", `Original form of 得. Depicts a hand (寸) grabbing a shell (貝), used as currency in ancient China, to convey the meaning "get".`, "obs", [iconComponent("貝", [0, 5]), iconComponent("寸", [5], "Here used to depict a hand.")]);
icon("得", "obtain; get; [particle]", `Originally written as 㝵. Depicts a hand (寸) grabbing a shell (貝), used as currency in ancient China, to convey the meaning "get". The 彳 (movement) component was added later.`, "bs", [meaningComponent("彳", [0, 3]), iconComponent("貝", [3, 8]), iconComponent("寸", [8], "Here used to depict a hand.")]);
let shiDescription = `The characters 史 (history), 吏 (government official), 使 (cause; use; instruct), and 事 (matter; work; affair) are all etymologically related and all derive from the same ancient character, depicting a hand (又) holding some object. 
There are various theories about theories about what this object is, including a writing utensil, a container for official documents, a flag, or a hunting tool.
These four characters were originally all written the same, but later marks were added to distinguish them.`;
let shiObject = `Unkown object. Possibly a writing utensil, a container for official documents, a flag, or a hunting tool.`;
icon("史", "history", shiDescription, "obs", [unknownComponent(O, [0, 4], shiObject), iconComponent("又", [4], "Depicts a hand.")]);
icon("吏", "government official", shiDescription, "obs", [unknownComponent(O, [0, 5], shiObject), iconComponent("又", [5], "Depicts a hand.")]);
icon("使", "cause; use; instruct", shiDescription, "obs", [meaningComponent("亻", [0, 2]), unknownComponent(O, [2, 7], shiObject), iconComponent("又", [7], "Depicts a hand.")]);
icon("事", "matter; work; affair", shiDescription, "obs", [unknownComponent(O, [0, 4, 7], shiObject), iconComponent("又", [4, 7], "Depicts a hand.")]);
phonsem("您", "你", "心", 7, "you", "", false, true);
icon("𡈼", "stand upright (tǐng)", "Pictograph of a person standing upright.", "o");
icon("廴", "long stride", "Depicts a long stride.", "s");
phonsem("廷", "𡈼", "廴", 4, "palace courtyard");
semphon("挺", "扌", "廷", 3, "erect; stick out");
icon("直", "straight", "Pictograph of a straight line coming from the eye, depicting somone looking straight at something. An additional stroke was added at the bottom for unkown reasons.", "obs", [iconComponent(O, [0, 2], "Depicts a straight line"), iconComponent("目", [2, 7]), unknownComponent(O, [7], unknownComonentNote())]);
addEtymology("德", "virtue; morality", "Depicts walking (彳) through life with a straight (直) heart (心) to represent the meaning \"virtue\".", [meaningComponent("彳", [0, 3]), meaningComponent("直", [3, 11]), meaningComponent("心", [11])], "bs");
icon("耳", "ear", "Pictograph of an ear.", "obs");
addEtymology("聽", "hear; listen", "Phonosemantic compound. 耳 (ear) represents the meaning and 𡈼 (tǐng) and 德 represent the sound. This character is unusual because it has multiple sound components.", [meaningComponent("耳", [0, 6]), soundComponent("𡈼", [6, 10]), soundComponent("德", [10], "The left 彳 (walk) component of 德 is omitted here. " + obsoleteSound("聽", "德"))]);
icon("丁", "robust", `Pictograph of a nail, which is now written as 釘.`, "obs");
semphon("釘", "金", "丁", 8, "nail");
simp("钉", "釘", [[0, 5], [5]]);
semphon("廳", "广", "聽", 3, "hall; large room");
semphon("厅", "广", "丁", 2, "hall; large room", simplified("廳"));
icon("斤", "axe", "Pictograph of an axe.", "ob");
semphon("听", "口", "厅", 3, "hear; lister", simplified("聽") + " The right side looks like 斤 (axe) but is actually a corruption of 厅.");
semphon("話", "言", "舌", 7, "language; talk");
simp("话", "話", [[0, 2], [2]]);
icon("雨", "rain", "Pictograph of rain falling from a cloud.", "obs");
icon("而", "and; but; yet", "Originally a pictograph of a beard, now written as 耏. The current use as a conjunction is a phonetic loan.", "ob");
icon("彡", "hair", "Pictograph of strands of hair.")
addEtymology("耏", "beard", "Phonosemantic compound. 而 represents the sound and 彡 (hair) represents the meaning.");
addEtymology("需", "require; need", `Originally was a pictograph of a person standing under the rain (雨), representing the meaning "to get wet", now written as 濡.
The current meaning is a phonetic loan. The person component was later replaced with the phonetic component 而.`, [iconComponent("雨", [0, 8]), soundComponent("而", [8], obsoleteSound("需", "而"))], "bs")
addEtymology("濡", "beard", "Phonosemantic compound. 氵 (water) represents the meaning and 需 represents the sound.");
icon("豆", "bean; (bowl)", "Pictograph of a stemmed bowl. Current meaning is a phonetic loan.", "obs");
icon("丰", "abundant; fertile", "Pictograph of a growing plant.", "bs");
icon("壴", "drum", "Pictograph of a drum with some sort of decoration on top.", "obs", [iconComponent(O, [0, 2], "Depicts a decoration on top of the drum."), iconComponent("豆", [2], "Depicts the bowl-shaped base of the drum.")]);
icon("豐", "abundant; fertile", "Pictograph of a pot floruishing with plants.", "bs", [iconComponent("丰", [1, 5]), iconComponent("丰", [5, 9]), iconComponent("豆", [9], "Here used to represent a pot.")]);
addEtymology("封", "close; seal")
phonsem("封", "丰", "寸", 6, "seal; close", "", false, false, "b");
phonsem("邦", "丰", "⻏", 4, "nation; state");
phonsem("帛", "白", "巾", 5, "silk");
phonsem("幫", "封", "帛", 9, "help; support", obsoleteMeaning("upper part of a shoe"));
phonsem("帮", "邦", "巾", 6, "help; support", simplified("幫") + " " + obsoleteMeaning("upper part of a shoe"));
icon("亡", "die; flee", "Pictograph of the tip of a knife blade.", "bs");
semphon("忙", "忄", "亡", 3, "busy");
semsem("戔", "戈", "戈", 4, "narrow; small", `Combination of two weapons (戈), based on the original meaning "destroy", now written as 殘.`);
simp("戋", "戔", [[0, 1], [1]]);
icon("歹", "bad; evil", "Origin unclear. Possibly represents remnants from a carcass.", "o");
semphon("殘", "歹", "戔", 4, "destroy; injure");
simp("残", "殘");
semphon("錢", "金", "戔", 8, "money");
simp("钱", "錢", [[0, 5], [5]]);
icon("䧹", "eagle (yīng)", "Pictograph of an eagle perched on a branch. Original form of 鷹.", "o", [iconComponent("爿", [0, 5], "Depicts a branch."), iconComponent("隹", [5])]);
icon("片", "slice; thin piece", "Pictograph of a slice of a tree, taken from the right half of 木 (tree).");
icon("爿", "piece of wood", "Mirror image of 片 (slice; thin piece). Pictograph of a slice of a tree, taken from the left half of 木 (tree).")
icon("鳥", "bird", "Pictograph of a bird.", "obs");
simp("鸟", "鳥");
phonsem("鷹", "䧹", "鳥", 13, "eagle; hawk; falcon", "", false, true);
phonsem("鹰", "䧹", "鸟", 13, "eagle; hawk; falcon", simplified("鷹"), false, true);
phonsem("應", "䧹", "心", 13, "should; must; agree");
simp("应", "應", [[6], [0, 6]]);
semphon("該", "言", "亥", 7, "should; ought; probably");
simp("该", "該", [[0, 2], [2]]);
icon("垂", "hang down; droop", "Pictograph of drooping branches.", "os");
semphon("睡", "目", "垂", 5, "sleep");
semphon("跟", "足", "艮", 7, "follow; together with; heel");
semphon("吧", "口", "巴", 3, "[suggestion particle]");
icon("己", "self", "Origin unclear.");
icon("已", "already; finish", "Origin unclear.");
icon("自", "self; from; since", "Pictograph of a nose. In China, when people point to themselves, they typically point to their nose.", "obs");
icon("走", "walk; go", "Pictograph of a person swaying their arms while walking.", "bs", [iconComponent(O, [0, 3], "Depicts a person swaying their arms."), meaningComponent("龰", [3])]);
semphon("起", "走", "己", 7, "rise; get up");
icon("㐅", "five", "Archaic variant of 五 (five).");
let 學_msg = `Originally composed of the numbers five (㐅) and six (六), representing study of arithmetic. 
Later two hands (又) were added on the left and right side of the character, possibly depicting counting with fingers or hands-on teaching.
Finally a child (子) was added to the bottom, depicting a child being educated.
The bottom part of 六 (six) was reanalyzed as 宀 (roof) and interpreted as a building for learning.`;
icon("學", "learn; study", 學_msg, "obs", [iconComponent("㐅", [4, 6]), iconComponent("六", [6, 8]), iconComponent("又", [0, 4]), iconComponent("又", [8, 11]), iconComponent("宀", [11, 13]), iconComponent("子", [13])]);
icon("学", "learn; study", simplified("學") + " " + 學_msg, "學:obs", [simplifiedComponent(O, [0, 3], "Shorthand form of the 㐅 (five), 六 (six), and 又 (hand) components in the top part of the traditional character 學."), iconComponent("宀", [3, 5]), iconComponent("子", [5])]);
phonsem("覺", "學", "見", 13, "think; perceive; sleep", "Only the top part of 學 is used, which prevents the character from being too crowded.");
phonsem("觉", "学", "见", 5, "think; perceive; sleep", simplified("學") + " Only the top part of 学 is used, which prevents the character from being too crowded.");
icon("襄", "help; assist", "Origin unclear.", "b");
semphon("讓", "言", "襄", 7, "let; permit");
semphon("让", "讠", "上", 2, "let; permit", simplified("讓"));
icon("戶", "door", "Pictograph of a door, taken from the left half of 門.", "os");
phonsem("所", "戶", "斤", 4, "place; that which", "The contribution of 斤 (axe) to the meaning is unclear.", true);
semsem("等", "⺮", "寺", 6, "class; rank; wait", "Higher-class people in ancient China who worked in temples (寺) wrote on bamboo (⺮) strips.");
semphon("談", "言", "炎", 7, "chat; discuss", "", true);
semphon("谈", "讠", "炎", 2, "chat; discuss", simplified("談"), true);
icon("禾", "grain", "Pictograph of grain.", "ob");
phonsem("和", "禾", "口", 5, "and; together; harmony", mouthedNote);
icon("工", "work; craft", "Pictograph of a carpenter's tool.", "ob");
icon("弓", "bow (archery)", "Pictograph of a curved bow.", "bs");
icon("發", "send out; to issue", `Depicts a person standing on their two feet, pulling back a bowstring, about to shoot an arrow. Conveys the meaning "shoot; send out".`, "os", [iconComponent("止", [0, 2], "Left foot. Mirror image of 止."), iconComponent("止", [2, 5], "Right foot."), iconComponent("弓", [5, 8]), iconComponent(O, [8, 10], "Depicts a bowstring being pulled back."), iconComponent("又", [10])]);
icon("髮", "hair", "Originally a combination of 首 (head) and 犬 (dog), both of which are hairy. Later the 首 (head) component was separated into the separate components 镸 (long) and 彡 (hair).", "bs", [iconComponent("镸", [0, 7]), iconComponent("彡", [7, 10]), iconComponent("犬", [10])]);
icon("发", "send out; hair", "Simplified form of both 發 (send out; to issue) and 髮 (hair). Derived from 犬 (dog), the bottom component of 髮.");
icon("生", "be born; life", "Pictograph of a sprout emerging from the ground.", "obs");
icon("网", "net", "Pictograph of a net.", "o");
semphon("罔", "网", "亡", 5, "net");
semphon("網", "糹", "罔", 6, "net", "", false, true);
phonsem("頭", "豆", "頁", 7, "head");
addEtymology("头", "head", "Phonosemantic compound. 頁 represents the meaning and 豆 represents the sound. " + cursive("头", "頭"), [simplifiedComponent("豆", [0, 2]), simplifiedComponent("頁", [2])], "頭:tc");
icon("買", "buy", "Pictograph of money (貝) coming out of a netted bag (网).", "obs", [iconComponent("网", [0, 5]), iconComponent("貝", [5], "Shells were used as currency in ancient China.")]);
simp("买", "買", [[0, 1], [1]], {}, { "貝": "头" }, true);
semphon("賣", "出", "買", 3, "sell", "", false, true, false, "s");
semphon("卖", "出", "买", 2, "sell", simplified("賣"), false, true, false, "賣:s");
semphon("讀", "言", "賣", 7, "read", "", true);
semphon("读", "讠", "卖", 2, "read", simplified("讀"), true);
phonsem("過", "咼", "辶", 9, "go over; cross");
simp("过", "過", [[3], [0, 3]], {}, { 咼: "寸" }, true);
icon("旦", "dawn; morning", "Pictograph of the sun rising above the horizon.", "", [iconComponent("日", [0, 4]), iconComponent(O, [4], "Depicts the horizon.")]);
semphon("但", "亻", "旦", 2, "but; only");
icon("間", "between; space; gap", "Depicts sunlight (日) shining through the gap in a door (門).", "", [iconComponent("門", [0, 8]), iconComponent("日", [8])]);
simp("间", "間", [[0, 3], [3]], { 門: "门" });
semphon("簡", "⺮", "間", 6, "simple", obsoleteMeaning("bamboo strips for writing"));
simp("简", "簡", [[0, 6], [6]], { 間: "间" });
icon("井", "water well", "Pictograph of a well.", "o");
semphon("青", "生", "井", 4, "color of nature; green; blue");
semphon("情", "忄", "青", 3, "feeling; situation");
semphon("請", "言", "青", 7, "ask; invite; please");
simp("请", "請", [[0, 2], [2]], { 言: "讠" });
semphon("找", "扌", "戈", 3, "find; look for", "", true);
icon("正", "straight; correct", `Pictograph of a foot (止) heading toward a city. Based on the original meaning "go on a military campaign", now written as 征. The meaning later shifted to "power", "rule" (政), and "correct" (正).`, "ob", [iconComponent(O, [0, 1], "Depicts a city."), iconComponent("止", [1])]);
semphon("征", "彳", "正", 3, "journey; campaign; attack", "Originally written as 正.");
phonsem("政", "正", "攵", 5);
icon("从", "from; follow", "Pictograph of one person following another.", "s");
icon("從", "from; follow", "Originally a pictograph of one person following another (从).  Later the 彳 and 止 components were added to indicate movement.", "b", [iconComponent("彳", [0, 3]), iconComponent("从", [3, 7], "Depicts one person following another."), iconComponent("止", [7])]);
icon("它", "it", "Pictograph of a snake, now written as 蛇. The current use as a pronoun is a phonetic loan.", "ob");
semphon("蛇", "虫", "它", 6, "snake", "Originally written as 它.");
icon("同", "same; together", "Pictograph of a bucket or tube, now written as 筒. " + mouthedNote, "obs", [iconComponent(O, [0, 3], "Depicts a bucket or tube. This meaning is now represented by 筒."), meaningComponent("口", [3])]);
semphon("筒", "⺮", "同", 6, "tube; cylinder", "Originally written as 同.");
phonsem("意", "音", "心", 9, "idea; thought; wish");
icon("經", "pass through; undergo; classics", "Pictograph of a loom for weaving. In a loom threads have to pass through each other.", "bs", [meaningComponent("糹", [0, 6]), iconComponent(O, [6], "Depicts a loom.")]);
simp("经", "經", [[0, 3], [3]], { 糹: "纟" });
icon("丙", "3rd heavenly stem", "Origin unclear. Variously explained as a table or pedestal, or a fish tail.", "obs");
icon("兩", "two", "Combination of two 丙 characters. The significance of 丙 is unclear.");
simp("两", "兩");
icon("車", "car; vehicle", "Pictograph of a chariot.", "obs");
simp("车", "車", null, {}, {}, true);
icon("年", "year", "Pictograph of a person (卩) harvesting grain (禾). The harvest season is a yearly event. The components are not obvious in the modern form.", "obs", [iconComponent("禾", [0, 2, 4, 5]), iconComponent("卩", [2, 4, 5])]);
icon("牛", "cow", "Pictograph of the head of a cow.", "ob");
semsem("件", "亻", "牛", 2, "item", "The correspondence between the components 亻(person) 牛 (cow) and the character 件 (item) is unclear.");
icon("東", "east", `Pictograph of a basket or a bag. The current meaning "east" is a phonetic loan.`, "obs");
simp("东", "東", null, {}, {}, true);
icon("重", "heavy; repeat", "Pictograph of a person (亻) carrying a heavy basket (東).", "bs", [iconComponent("亻", [0, 1, 6, 7]), iconComponent("東", [1, 6, 7], "Here used to depict a basket.")]);
icon("取", "take; get", "Pictograph of a hand (又) grabbing an ear (耳). In ancient China, the ears of opponents in battle were cut off and collected as tokens of victory.", "ob", [iconComponent("耳", [0, 6]), iconComponent("又", [6])]);
semphon("最", "冃", "取", 4, "most; -est", "冃 is used here since a hat is placed at the highest part of the head.", true);
icon("后", "empress; (simp.) after, behind", "后 (empress) and its mirror image 司 (take charge) were originally used interchangeably. The origin of both characters is unclear. " + simplifyMerge("后", "後", "after, behind"));
icon("司", "take charge; manage", "司 (take charge) and its mirror image 后 (empress) were originally used interchangeably. The origin of both characters is unclear.");
addEtymology("後", "after; behind", "Phonosemantic compound. 幺 represents the sound, and 彳 (walk) and 夂 (foot) are used together to depict following behind someone.", [meaningComponent("彳", [0, 3]), soundComponent("幺", [3, 6]), meaningComponent("夂", [6])]);
icon("告", "tell; say", "Pictograph of a tongue extending from an open mouth. Graphically similar to 舌 (tongue).", "os", [iconComponent(O, [0, 4], "Depicts a tongue extending from an open mouth."), iconComponent("口", [4])]);
icon("屰", "contrary; oppose", "Pictograph of an upside-down person. Original form of 逆.", "obs");
semsem("逆", "屰", "辶", 6, "contrary; oppose; go against", "Originally written as 屰, a pictograph of an upside-down person. The 辶 (walk) component was added later.", "b");
addEtymology("斥", "blame; reprimand", "Originally written as 㡿. Composed of 广 (roof) and 屰 (contrary; oppose). The purpose of the 广 component is unclear.", [unknownComponent("广", [0, 2]), meaningComponent("屰", [2], "Shorthand form of 屰 (contrary; oppose).")], "s");
addEtymology("㡿", "blame; reprimand", "Archaic variant of 斥. Composed of 广 (roof) and 屰 (contrary; oppose).", [], "斥:s")
semphon("訴", "言", "斥", 7, "tell; accuse; complain", "", true, true);
simp("诉", "訴", [[0, 2], [2]], { 言: "讠" });
semsem("信", "亻", "言", 2, "trust; letter; information", "Conveys trusting (信) what a person (人) says (言).");
semphon("給", "糹", "合", 6, "give; for; provide", "The 糸 (silk) component is used because silk is a precious material often given as a gift.", true);
simp("给", "給", [[0, 3], [3]], { 糹: "纟" });
icon("午", "noon; 7th earthly branch", "Pictograph of a pestle used for pounding rice, now written as 杵. The current meaning \"noon\" is a phonetic loan.", "obs");
semphon("杵", "木", "午", 4, "pestle; poke", "Originally written as 午, a pictograph of a pestle used for pounding rice.");
semphon("許", "言", "午", 7, "allow; perhaps");
simp("许", "許", [[0, 2], [2]], { 言: "讠" });
icon("舟", "boat", "Pictograph of a boat.", "obs");
icon("前", "forward; before", "Depicts a boat (舟) moving (止) forward (前).", "obs", [iconComponent("止", [0, 3]), iconComponent("舟", [3])]);
icon("面", "face; side; surface; (simp.) noodles", "Pictograph of the outline of a face, with an eye (目) in the middle. " + simplifyMerge("面", "麵", "noodles"), "os", [iconComponent(O, [0, 4, 8], "Depicts the outline of a face."), iconComponent("目", [4, 8])]);
semphon("麵", "麥", "面", 11, "noodles");
icon("久", "long time", "Origin unclear");
semphon("待", "彳", "寺", 3, "wait; stay", "", true);
semphon("著", "艹", "者", 3, "[progress particle]; touch, wear; show");
simp("着", "著", [[0, 3], [3]]);
icon("主", "owner; master; main", "Pictograph of a torch, now written as 炷. The current meaning is a phonetic loan.", "os");
semphon("炷", "火", "主", 4, "wick for oil lamp; burn; incense stick", "Originally written as 主, a pictograph of a torch.");
semphon("住", "亻", "主", 2, "live; stay");
icon("方", "square; direction; side", "Origin unclear. Variously explained as a pictograph of a square tool, a part of a knife, or a raft.", "obs");
semphon("房", "戶", "方", 4, "room; house");
addEtymology("將", "will; use; take", `Depicts a hand (寸) taking a piece of meat (肉), conveying the meaning "take". 爿 (qiáng) is a sound component.`, [soundComponent("爿", [0, 4]), iconComponent("肉", [4, 8]), iconComponent("寸", [8], "Used here to depict a hand.")]);
simp("将", "將", [[0, 3], [3, 6], [6]], { 爿: "丬" });
icon("欠", "yawn; lack; owe", "Pictograph of a person opening their mouth to yawn.", "os", [iconComponent(O, [0, 2], "Depicts an open mouth."), iconComponent("人", [2])]);
addEtymology("次", "time; next; second", "", [meaningComponent("二", [0, 2]), unknownComponent("欠", [2])]);
icon("父", "father", "Pictograph of a hand holding something. There are various theories about what the object being held is, including a hatchet (now written as 斧), or a rod.", "bs");
phonsem("斧", "父", "斤", 4, "hatchet");
phonsem("布", "父", "巾", 2, "cloth; declare", "In the modern form it is not obvious that the top component is 父.", false, false, "b");
icon("爻", "intertwined cross shape; diagram for divination", "Pictograph of two X shapes.");
addEtymology("希", "hope", `Composed of 爻 (intertwined cross shape) and 巾 (cloth). Conveys a rare type of stitched cloth, corresponding to the original meaning "sparse; rare". The meaning later shifted to "hope".`, [iconComponent("爻", [0, 4]), meaningComponent("巾", [4])]);
addEtymology("望", "hope; expect; gaze", "Pictograph of a person standing up (𡈼) and gazing at the moon (月). 亡 is a sound component that was added later.", [soundComponent("亡", [0, 3]), iconComponent("月", [3, 7]), iconComponent("𡈼", [7])], "os");
semphon("機", "木", "幾", 4, "machine; opportunity");
simp("机", "機", [[0, 4], [4]], { 幾: "几" });
icon("昔", "former times; ancient", "Pictograph of the sun (日) having passed through many cycles of rising and setting.", "b", [iconComponent(O, [0, 4], "Depicts cycles of rising and setting."), iconComponent("日", [4])]);
semphon("錯", "金", "昔", 8, "mistake; wrong; complex", `The character is based on the original meaning "grind stone", which later shifted to "mix", "be in disorder", and "wrong".`, true);
simp("错", "錯", [[0, 5], [5]], { 金: "钅" });
icon("堇", "clay", "Pictograph of a person over a fire with their mouth open upwards. The original meaning of this character is unclear.", "bs", [iconComponent("口", [0, 4], "Depicts a mouth open upwards."), iconComponent("人", [4, 10], "Stick figure of a person."), iconComponent("火", [10])]);
semphon("漢", "氵", "堇", 3, "Han river; Chinese", "", true);
semphon("僅", "亻", "堇", 2, "only");
phonsem("難", "堇", "隹", 11, "difficult", obsoleteMeaning("type of bird"), true);
simp("汉", "漢", [[0, 3], [3]], {}, { 堇: "又" }, true);
simp("仅", "僅", [[0, 2], [2]], {}, { 堇: "又" }, true);
simp("难", "難", [[2], [0, 2]], {}, { 堇: "又" }, true);
icon("必", "certainly; must", "Pictograph of a weapon, now written as 柲. The current meaning is a phonetic loan.", "b");
addEtymology("柲", "bamboo weapon handle", `Phonosemantic compound. 木 represents the meaning and 必 represents the sound. Originally written as 必, a pictograph of a weapon.`);
icon("須", "must", "Pictograph of a person with a bearded face. The current meaning is a phonetic loan.", "ob", [iconComponent("彡", [0, 3]), iconComponent("頁", [3], "Depicts a head.")]);
icon("鬚", "beard", "Originally written as 須, a pictograph of a person with a bearded face. The components 镸 (long) 彡 (hair) were added later.", "", [iconComponent("镸", [0, 7]), iconComponent("彡", [7, 10]), soundComponent("須", [10])]);
simp("须", "須", [[0, 3], [3]], { 頁: "页" }, {}, false, "鬚", "beard");
icon("角", "horn; corner; angle", "Pictograph of a horn.", "obs");
semphon("确", "石", "角", 5, "solid; firm; real; true");
semphon("定", "宀", "正", 3, "stable; fixed; determine", "", true);
phonsem("如", "女", "口", 3, "if; as", mouthedNote, true);
icon("果", "fruit", "Pictograph of fruit growing on a tree.", "obs", [iconComponent(O, [0, 4], "Depicts fruit. Unrelated to the visually similar character 田 (field)."), iconComponent("木", [4])]);
icon("舁", "lift; raise", "Pictograph of four hands working together to lift something.", "bs", [iconComponent("又", [0, 3, 5, 6]), iconComponent("又", [3, 6]), iconComponent("又", [6, 8]), iconComponent("又", [6, 7, 8])]);
addEtymology("興", "rise; flourish; excitement", "Depicts four hands (舁) working together (同) to raise something.", [meaningComponent("舁", [0, 4, 10]), meaningComponent("同", [4, 10])], "bs");
simp("兴", "興", [[0, 1, 2], [1, 2]], {}, { 舁: "舁", 同: "同" }, true);
icon("非", "not", "Pictograph of two wings facing opposite directions.", "s");
phonsem("裳", "尚", "衣", 8, "lower garment", "Originally used interchangeably with 常.");
phonsem("常", "尚", "巾", 8, "often; ordinary", `Based on the original meaning, "lower garment", now written as 裳. The current meaning is a phonetic loan.`);
semsem("喜", "壴", "口", 9, "Depicts merriment from beating on a drum (壴) and singing with the mouth (口).");
icon("雚", "stork; heron", "Pictograph of a stork", "obs", [iconComponent("隹", [9])]);
phonsem("歡", "雚", "欠", 18, "joyous; happy", "欠 (yawn) is a pictograph of a person with an open mouth. Likely used here to represent a person joyfully laughing.");
simp("欢", "歡", [[2], [0, 2]], {}, { 雚: "又" });
semphon("法", "氵", "去", 3, "law; method; way", "The water (氵) component is used to represent the way water follows a defined path e.g. in rivers.");
icon("或", "maybe; or", "Originally a pictograph of a weapon. The current meaning is a phonetic loan.", "ob", [iconComponent("戈", [0, 1, 4]), meaningComponent("口", [1, 4], mouthedNote)]);
semphon("國", "囗", "或", [[0, 2, 10], [2, 10]], "country");
simp("国", "國", [[0, 2, 7], [2, 7]], {}, { 或: "玉" });
icon("中", "middle; center", `A line passing through the middle of a box, representing the meaning "middle".`);
phonsem("床", "广", "木", 3, "bed");
icon("母", "mother", `Pictograph of a woman kneeling, with two dots representing the two nipples that mothers use to feed their young.`, "obs");
icon("每", "each; every", "Pictograph of a woman (母) with a hairpin in her hair. In ancient China, women of marriagable age wore a hairpin. Based on the original meaning \"young woman\" The current meaning is a phonetic loan.", "ob", [iconComponent(O, [0, 2], "Depicts a hairpin."), iconComponent("母", [2])]);
icon("央", "beg; finish; middle", "Pictograph of a person (大) with a cangue (torture device for punishing criminals) around his neck. People wearing such devices were not able to reach their mouth with their own hands, and were forced to beg for food.", "os", [iconComponent(O, [0, 2], "Depicts a cangue (torture device for punishing criminals worn around the neck)."), iconComponent("大", [2], "Here used as a pictograph of a person")]);
semphon("英", "艹", "央", 3, "blossom; outstanding; hero");
phonsem("吾", "五", "口", 4, "(archaic) I; me");
semphon("語", "言", "吾", 7, "language; speech");
simp("语", "語", [[0, 2], [2]], { 言: "讠" });
icon("丩", "entangle; gather", "Pictograph of two ropes entangled together, now written as 糾.", "os");
semphon("糾", "糹", "丩", 6, "entangle; gather", "Originally written as 丩, a pictograph of two ropes entangled together.");
simp("纠", "糾", [[0, 3], [3]], { 糹: "纟" });
semphon("叫", "口", "丩", 3, "call; shout");
phonsem("句", "丩", "口", 2, "sentence; phrase");
semphon("夠", "多", "句", 6, "enough");
phonsem("够", "句", "多", 5, "enough");
icon("用", "use", `Originally a pictograph of a bucket with a handle on the right side. The current meaning "use" is a phonetic loan.`, "bs");
icon("元", "first; primary; currency unit", `Pictograph of a person with two lines added at the head area, representing the meaning the meaning "head" or "first".`, "ob");
semphon("完", "宀", "元", 3, "complete; finish", "The 宀 component is used because putting on a roof completes the process of constructing a building.");
icon("戊", "fifth Heavenly stem; battle-axe", "Pictograph of an axe. Similar to 戈, 戉, and 戌.", "obs");
phonsem("成", "丁", "戊", [[2, 3], [0, 2, 3]], "complete; succeed", `The 戊 (axe) component is used to represent defending a city. Based on the original meaning "city", now written as 城. The meaning later shifted to "build", "accomplish", and "complete".`, true);
semphon("城", "土", "成", 3, "city; city walls");
icon("入", "enter; go in", "Origin unclear. Variously explained a a pictograph of an entrance to a tent, or an arrow pointing forward.", "ob");
addEtymology("全", "complete; whole", "Origin unclear.", [unknownComponent("入", [0, 2]), unknownComponent("玉", [2])]);
semphon("把", "扌", "巴", 3, "hold; take; handle");
semphon("打", "扌", "丁", 3, "beat; hit", "", true);
phonsem("當", "尚", "田", 8, "be; act as; face; during", "The contribution of the 田 (field) component to the meaning is unclear.");
simp("当", "當", [[3], [0, 3]], {}, { 尚: "尚", 田: "田" }, true);
icon("廾", "two hands", "Pictograph of two hands.", "o");
icon("開", "open", "Pictograph of two hands opening the bolt on a door.", "s", [iconComponent("門", [0, 8]), iconComponent(O, [8, 9], "Depicts a bolt on a door."), iconComponent("廾", [9])]);
simp("开", "開", [[0, 0], [0, 1], [1]]);
icon("申", "extend; state; explain", "Pictograph of a lightning bolt. The current meaning is a phonetic loan.", "obs");
icon("电", "electricity; lightning", "Originally a variant form of 申, a pictograph of a lightning bolt. The traditional form 電 adds the 雨 (rain) component.", "申:obs");
semsem("電", "雨", "电", 8, "electricity, lightning", "Depicts lightning (电) during a rainstorm (雨).");
phonsem("台", "以", "口", 2, "platform; station; (simp.) table; counter", mouthedNote + " " + simplifyMerge("台", "檯", "table; counter"), true);
semphon("室", "宀", "至", 3, "room");
semsem("臺", "高", "室", 6, "platform; station", "Only part of the 高 (tall) component is used, preventing the character from being too crowded.");
semphon("檯", "木", "臺", 4, "table; counter");
semphon("始", "女", "台", 3, "start; begin", "The 女 (woman) component is used because life begins inside a woman.", true);
phonsem("更", "丙", "攴", [[0, 5], [5]], "change; even more", "", true, false, "s");
icon("冰", "ice", "Pictograph of ice cubes (冫) next to a river of water (水).", "b", [iconComponent("冫", [0, 2], "Depicts ice cubes."), meaningComponent("水", [2])]);
semphon("決", "氵", "夬", 3, "decide; determine", `Based on the original meaning "burst open". The meaning later shifted to "clear", "cut off", "decide" and "judge".`, true, true);
simp("决", "決", [[0, 2], [2]], {}, { 氵: "冫" });
semphon("星", "日", "生", 4, "star; celestial object");
icon("其", "its; their; that", "Pictograph of a basket, now written as 箕. The current meaning is a phonetic loan.", "s");
semphon("箕", "⺮", "其", 6, "winnow basket", "Originally written as 其, a pictograph of a basket.");
phonsem("期", "其", "月", 8, "period of time");
icon("比", "compare", `Pictograph of two people side-by-side, conveying the meaning "to put together", "match", or "compare".`, "bs", [iconComponent("人", [0, 2]), iconComponent("人", [2])]);
icon("离", "mythical beast; (simp.) leave; depart; away from", "Pictograph of a legendary mountain demon with horns and a tail beween its legs, now written as 魑. The traditional character 離 (leave; depart; away from) was simplified to 离 by deleting the 隹 (bird) component.", "s");
phonsem("離", "离", "隹", 10, "leave; depart; away from", "The 隹 (bird) component alludes to a bird flying away.");
icon("鬼", "ghost; demon", "Pictograph of a human-like being with an unnatural head and a tail.", "obs", [iconComponent(O, [0, 5], "Depicts the head of a ghost/demon."), iconComponent("人", [5, 7]), iconComponent(O, [7], "Depicts a tail.")]);
semphon("魑", "鬼", "离", 9, "mountain demon");
icon("美", "beautiful", "Pictograph of a person with ornamental headwar.", "obs", [iconComponent(O, [0, 6], "Depicts ornamental headwear."), iconComponent("大", [6], "Used here as a pictograph of a person.")]);
icon("長", "long; grow; elder", "Pictograph of a person with long hair.", "obs");
simp("长", "長", null, {}, {}, true);
icon("丱", "two tufts of hair; young", "Pictograph of a child's hairstyle with two tufts.");
icon("𢇇", "weave threads - guān", "Depicts weaving threads (𢆶) through a weaving shuttle (丱).");
semphon("關", "門", "𢇇", 8, "shut; turn off; involve");
simp("关", "關", [[0, 0], [0]], {}, { "𢇇": "关" }, true);
semphon("聯", "耳", "𢇇", 6, "connect; join; unite", "Depicts earrings joined to the ear.", true);
simp("联", "聯", [[0, 6], [6]], {}, { "𢇇": "关" });
semsem("肰", "⺼", "犬", 4, "dog meat", "Depicts the meat (⺼) of a dog (犬).");
phonsem("然", "肰", "灬", 8, "correct; so; thus", `Based on the original meaning "ignite; burn", now written as 燃. The current meaning is a phonetic loan.`);
semphon("燃", "火", "然", 4, "ignite; burn");
icon("壬", "ninth Heavenly stem", "Origin unclear.", "obs");
semphon("任", "亻", "壬", 2, "assign; appoint; responsibility", "", false);
semphon("何", "亻", "可", 2, "what; how; why");
icon("西", "west", "Origin unclear. Variously explained as a bag or bird's nest.", "ob");
icon("鹵", "salt", "Pictograph of a bag of salt.", "bs");
simp("卤", "鹵");
icon("戌", "11th earthly branch", "Pictograph of an axe. Similar to 戈 and 戊.", "obs");
addEtymology("咸", "all; together; (simp.) salty", `Depicts a massacre with a weapon (戌), based on the original meaning "slaughter; terminate". The meaning later shifted to "finish", "complete", and "all". ` + simplifyMerge("咸", "鹹", "salty"), [meaningComponent("戌", [0, 3, 6]), unknownComponent("口", [3, 6], "Likely used to distinguish this character from 戌.")], "obs");
semphon("鹹", "鹵", "咸", 11, "salty");
phonsem("感", "咸", "心", 9, "feel; touch; emotion", "", true);
icon("射", "shoot", "Depicts a hand pulling back a bowstring with an arrow to shoot.", "bs", [iconComponent(O, [0, 7], "Depicts a bow and arrow. Originally unrelated to 身 (body), but later written the same."), iconComponent("寸", [7], "Depicts a hand.")]);
icon("身", "body", `Pictograph of a person with an protruding midsection. The protruding midsection is variously explained as (1) representing the main part of a person's body, or (2) as representing a pregnant woman that has a body inside her body.`, "bs");
semphon("謝", "言", "射", 7, "thanks");
simp("谢", "謝", [[0, 2], [2]], { 言: "讠" });
icon("失", "lose", "Pictograph of something falling out of the hand.", "s", [iconComponent("手", [0, 3, 4]), iconComponent(O, [3, 4], "Depicts an object falling out of the hand.")]);
icon("妻", "wife", "Pictograph of a hand grabbing a woman's hair. In ancient China, women of marriagable age wore hairpins (compare with 每).", "bs", [iconComponent(O, [0, 1, 4, 5], "Depicts a hairpin."), iconComponent("又", [1, 4], "Depicts a hand grabbing the woman's hair."), iconComponent("女", [5])]);
icon("辛", "hard; laborious; suffering", "Pictograph of a chisel-like tool used to tatoo the face of criminals as punishment (see 黑).", "bs");
semsem("妾", "辛", "女", 5, "concubine", `Depicts a woman (女) with a damaged reputation (辛 is a pictograph of a tool used to tatoo the face of criminals as punishment).`);
semphon("接", "扌", "妾", 3, "recieve; meet; connect");
icon("且", "moreover", `Originally a pictograph of a sacrificial altar. The current meaning "moreover" is a phonetic loan.`, "ob");
phonsem("助", "且", "力", 5, "help", "", true);
semphon("種", "禾", "重", 5, "seed; grow; type");
semphon("种", "禾", "中", 5, "seed; grow; type", simplified("種"));
icon("分", "separate; divide", `Depicts a knife ( 刀 ) being used to cut two things apart (八).`, "", [iconComponent("八", [0, 2], "Depicts two things being separated."), iconComponent("刀", [2])]);
semphon("童", "辛", "重", [[0, 5, 7, 8, 9, 10], [4]], "child", `Based on the original meaning "young servant boy". The meaning later shifted to "child".`);
semphon("鐘", "金", "童", 8, "clock; bell");
semphon("钟", "钅", "中", 5, "clock; bell", simplified("鐘"));
icon("冓", "meet; confluence", "Pictograph of two fish facing each other.", "bs");
semphon("講", "言", "冓", 7, "speak; explain", "", true);
semphon("讲", "讠", "井", 2, "speak; explain", simplified("講"));
icon("泉", "spring of water", "Pictograph of water flowing out of a spring.", "os", [iconComponent(O, [0, 5], "Depicts a spring. Unrelated to 白 (white)."), iconComponent("水", [5])]);
semsem("原", "厂", "泉", 2, "original; source; former", `Depicts a spring (泉) originating (原) from a cliff (厂).`);
semphon("源", "氵", "原", 3, "source; origin", "", false, true);
phonsem("愿", "原", "心", 10, "sincere; (simp.) hope; wish", simplifyMerge("愿", "願", "hope; wish"));
phonsem("願", "原", "頁", 10, "hope; wish", "The 頁 (head) component is used because wishes originate from the brain.");
icon("先", "first; early", `Depicts a person (人) stepping forward (止) leading the way.`, "ob", [iconComponent("止", [0, 4]), iconComponent("人", [4])]);
icon("老", "old", "Pictograph of an old person with long hair bent over and leaning on a cane.", "obs", [iconComponent(O, [0, 2], "Depicts long hair."), iconComponent(O, [2, 4], "Depicts an old man bent over."), iconComponent(O, [4], "Depicts a cane.")]);
semsem("名", "夕", "口", 3, "name; fame", `Traditionally explained as identifying youself at night (夕) by saying (口) your name (名) because is too dark for others to see you.`);
semphon("字", "宀", "子", 3, "letter; symbol; word", `The 宀 (roof) component is based on the original meaning "raise; nurture". The menaing later shifted to "educate", "word", and "writing".`);
icon("少", "less; few", `Pictograph of four small dots, representing grains of sand or rice, to convey the meaning "less". Similar to 小.`, "obs");
icon("系", "system; link; connection", "Pictograph of a hand (又) holding a group of threads (糸) that are connected together (系).", "bs", [iconComponent("又", [0, 1]), iconComponent("糸", [1])]);
semphon("係", "亻", "系", 2, "connect; tie; bind");
icon("服", "clothes; take; eat; obey; serve", "Pictograph of a person being served a plate.", "bs", [iconComponent(O, [0, 4], "Depicts a plate."), iconComponent("卩", [4, 6]), iconComponent("又", [6])]);
icon("卯", "mortise; 4th earthly branch", "Origin unclear. Variously explained as a mortise (a slot cut into a piece of wood), and knives used for sacrificing animals.", "obs");
phonsem("留", "卯", "田", 5, "stay; keep", "", true);
icon("坐", "sit", "Pictograph of two people (人) sitting on the ground (土).", "s", [iconComponent("人", [0, 2]), iconComponent("人", [2, 4]), iconComponent("土", [4]),]);
icon("因", "because; reason", "Pictograph of clothing surrounding (囗) a person (人), now written as 裀. The current meaning is a phonetic loan.", "bs", [iconComponent("囗", [0, 2, 5], "Depicts clothing surrounding a person."), iconComponent("大", [2, 5], "Depicts a person.")]);
addEtymology("裀", "undergarment; mat", `Phonosemantic compound. 衤 represents the meaning and 因 represents the sound. Originally written as 因, a pictograph of clothing surrounding a person.`);
semphon("律", "彳", "聿", 3, "law");
icon("示", "show; reveal", `Origin unclear. Most likely depicts some object of spiritual significance. Most often explained as an altar or a memorial tablet.`, "os");
phonsem("視", "礻", "見", 4, "look at; inspect");
simp("视", "視", [[4], [0, 4]], { 見: "见" });
icon("𠂤", "heap; pile; buttocks", "Pictograph of buttocks.", "ob");
icon("帀", "circle; surround; everywhere", "Origin unclear.");
addEtymology("師", "teacher; master; expert", "Origin unclear.", [unknownComponent("𠂤", [0, 6]), unknownComponent("帀", [6])]);
simp("师", "師", [[0, 2], [2]], {}, { "𠂤": "刂" });
addEtymology("帥", "handsome; smart; commander", `Originally a pictograph of two hands pulling a rod, based on the original meaning "lead; command". The meaning later shifted to "handsome". The purpose of the 巾 (cloth) is unclear. It possibly represents a special cloth worn by commanders.`, [iconComponent(O, [0, 6], "Depicts something being pulled by two hands. Unrelated to the 𠂤 (heap; pile; buttocks) component even though it looks identical in the modern form."), unknownComponent("巾", [6], "Possibly represents a special cloth worn by a commander.")], "bs");
simp("帅", "帥", [[0, 2], [2]], {}, { [O]: "刂" });
semphon("景", "日", "京", 4, "bright; scenery");
phonsem("影", "景", "彡", 12, "shadow; image; picture", "The 彡 component depicts lines of shadow.");
phonsem("進", "隹", "辶", 8, "go forward; advance", "", true);
phonsem("进", "井", "辶", 4, "go forward; advance", simplified("進"));
icon("立", "stand; establish", `Pictograph of a person standing on the ground.`, "obs");
semphon("站", "立", "占", 5, "station; stop; stand");
semphon("爸", "父", "巴", 4, "dad; father");
icon("殳", "spear", "Pictograph of a hand holding a spear.", "obs", [iconComponent(O, [0, 2], "Depicts a spear."), iconComponent("又", [2], "Depicts a hand.")]);
addEtymology("殹", "(archaic) [particle]", "Original meaning unclear.", [unknownComponent(O, [0, 7], "Seems to depict an arrow in a container."), unknownComponent("殳", [7])]);
icon("酉", "10th earthly branch", "Pictograph of a container for wine.", "obs");
semphon("酒", "氵", "酉", 3, "alcoholic drink", "The 酉 component is a pictograph of a container for wine, so it also serves as a meaning component.", false, true);
phonsem("醫", "殹", "酉", 11, "medicine", "The 酉 component is a pictograph of a container for wine, which is sometimes used for medicinal purposes.");
simp("医", "醫", [[0, 0], [0]]);
icon("舄", "shoe, slipper", `Pictograph of a bird with its two wings opened. Based on the original meaning "magpie", now written as 鵲. The current meaning "shoe" is a phonetic loan.`, "bs");
phonsem("鵲", "昔", "鳥", 8, "magpie", "Originally written as 舄.");
simp("鹊", "鵲", [[8], [0, 8]], { 鳥: "鸟" });
semphon("寫", "宀", "舄", 3, "write", "The contribution of the 宀 (roof) component to the meaning is unclear. Perhaps used since writing is typically done indoors.");
simp("写", "寫", [[0, 2], [2]], {}, { 舄: "与" }, true);
icon("牙", "tooth", "Pictograph of teeth.", "bs");
semphon("與", "舁", "牙", [[0, 4, 7], [4, 7]], "and; together; take part", "", true);
simp("与", "與", [[0, 0], [0]]);
icon("云", "cloud", "Pictograph of clouds.", "o");
semphon("雲", "雨", "云", 8, "cloud", "", false, true);
phonsem("動", "重", "力", 9, "move");
simp("动", "動", [[4], [0, 4]], {}, { 重: "云" });
icon("囟", "top of skull; fontanel", "Pictograph of the top part of the skull.", "s");
icon("川", "river", "Pictograph of a river.", "obs");
addEtymology("腦", "brain; mind; head", "The brain is part of the body (⺼) composed of a system of pathways (巛) located inside of the skull (囟).", [meaningComponent("⺼", [0, 4]), iconComponent("巛", [4, 7], "Here used to represent the system of neural pathways in the brain, similar to a system of rivers."), iconComponent("囟", [7])]);
simp("脑", "腦", [[0, 4], [4, 4], [4]]);
icon("曰", "speak; say", "Pictograph of a line, representing speech, coming out of a mouth (口).", "o", [iconComponent("口", [0, 2, 3]), iconComponent(O, [2, 3], "Represents a line of speech coming out of the mouth.")]);
icon("丐", "beggar", "Origin unclear. Possibly depicts a beggar holding his hand out.", "bs");
icon("匃", "beggar", "Variant form of 丐. Origin unclear. Possibly depicts a beggar holding his hand out.", "丐:bs");
semphon("曷", "曰", "匃", 4, "why; how; what", "", true);
semphon("喝", "口", "曷", 3, "drink");
icon("各", "each; every", `Pictograph of a foot (夂) entering an opening, (口), the opposite of 出 (exit). Based on the original meaning "enter", unrelated to the current meaning "each", which is a phonetic loan.`, "ob", [iconComponent("夂", [0, 3]), iconComponent("口", [3])]);
semphon("客", "宀", "各", 3, "guest; customer");
addEtymology("票", "ticket; ballot", "Origin unclear.", [unknownComponent("覀", [0, 6]), unknownComponent("示", [6])]);
semphon("漂", "氵", "票", 3, "float; drift; elegant");
phonsem("亮", "京", "人", 7, "bright; clear; reveal", "Depicts a person (人) in a high place (京).", true, true, "s");
icon("阜", "mound; abundant", "Origin unclear. Possibly represents stepping stones on a mountain.", "s");
semphon("院", "阝", "完", 2, "courtyard; institution");
icon("弟", "younger brother", `Pictograph of a rope wrapped around a weapon. Relation to current meaning "younger brother" unclear.`, "bs", [iconComponent("戈", [0, 2, 5], "Depicts a weapon."), iconComponent(O, [2, 5], "Depicts a rope.")]);
semphon("第", "⺮", "弟", 6, "order; rank");
icon("步", "step", "Picrograph of one foot in front of another, depicting footsteps.", "obs", [iconComponent("止", [0, 4]), iconComponent("止", [4])]);
icon("戉", "battle-axe", "Pictograph of a battle-axe, similar to 戈, 戊, and 戌. Now written as 鉞.", "obs");
semphon("鉞", "金", "戉", 8, "battle-axe", "Originally written as 戉.", false, true);
simp("钺", "鉞", [[0, 5], [5]], { 金: "钅" });
semphon("歲", "步", "戉", [[0, 4, 6, 10], [4, 6, 10]], "years (of age)");
simp("岁", "歲", [[0, 3], [3]], {}, { 步: "山", 戉: "夕" }, true);
semphon("塊", "土", "鬼", 3, "lump; chunk; piece");
simp("块", "塊", [[0, 3], [3]], { 鬼: "夬" });
semphon("地", "土", "也", 3, "earth; ground; [particle]", "", true);
semphon("姐", "女", "且", 3, "older sister");
icon("丮", "catch", "Pictograph of a person with both hands outstretched.", "b");
icon("埶", "skill; art", "Pictograph of a person making a craft with both hands.", "ob", [iconComponent(O, [0, 8], "Depicts some sort of craft."), iconComponent("丮", [8], "Depicts a person holding out both hands.")]);
phonsem("熱", "埶", "灬", 11, "hot", "", true);
icon("㚔", "shackles; handcuffs", "Pictograph of shackles.", "o");
icon("執", "execute; grasp", "Pictograph of a person with hands (丮) bound by shackles (㚔).", "ob", [iconComponent("㚔", [0, 8]), iconComponent("丮", [8], "Depicts a person with two hands outstretched.")]);
simp("执", "執", [[0, 3], [3]], {}, { 㚔: "扌" });
simp("热", "熱", [[6], [0, 6]], {}, { 埶: "执" });
icon("飛", "fly", `Pictograph of a flying bird.`, "bs");
simp("飞", "飛");

for (let direction in radicals) {
    for (let char in radicals[direction]) {
        icon(char, etymologies[radicals[direction][char]].definition, radicalNote(char));
    }
}

// 新冷静公司外习惯校思
// 店商杯场边狗表准备体 // Alexis reading 12/20/2018

// 喂旅馆于其实员永远北
// 路眼睛头汉堡玩笑努桌
// 试处理幸运色菜报张消
// 息或干租乐啊放教猫零
// 随便之带送参加解茶丈
// 夫安椅号记主办室结束
// 穿变特礼物总被位务无
// 拿向跑通球提算病苹步
// 考虑像刚混蛋且死清楚
// 游戏哥界共求部受活弟
// 害怕标根简单声班近条
// 保证跳照片卖介药休除
// 千万迎管红亲周选择慢
// 平舞花懂洗票注计划担
// 查数妻奇怪空职业歌并
// 性坏利原牛包护入左右
// 恢复满风容易纸调船唱
// 建议妹似乎酒化旁轻节
// 奶指

// common components
//阝阝鳥鸟衤酉马禾车馬貝米車隹宀頁广礻飠饣欠穴页巾攵羊耳令雨非舟方衣各歹者工且革莫圭青皿鬼台气尚占肖田票羽辟艮合比冫牛交走昜俞包亥乍巴皮斤丁甫龙弓卑娄分昆扁奇尞尧此耒毛里周吾可见吉屯灬干召句由其果堇齒加